data:
  path: /tmp/math_Qwen2-7B-Instruct.parquet
  prompt_key: prompt
  response_key: responses
  data_source_key: data_source
  reward_model_key: reward_model
  extrainfo_key: extra_info
  indexes_key: index

custom_reward_function:
  do_majority_vote: False
  majority_n: 1
  path: null
  name: compute_score
